# This is a basic workflow to help you get started with Actions

name: pull-request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    types: [ opened, reopened, edited, synchronize ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call_commit_workflow:
    uses: thephat296/ImageLoader/.github/workflows/commit.yml@image-loader

